/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search.index'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as FavoritesIndexRouteImport } from './routes/favorites.index'
import { Route as CuisinesIndexRouteImport } from './routes/cuisines.index'
import { Route as RecipesIdRouteImport } from './routes/recipes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesIndexRoute = FavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuisinesIndexRoute = CuisinesIndexRouteImport.update({
  id: '/cuisines/',
  path: '/cuisines/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdRoute = RecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/cuisines/': typeof CuisinesIndexRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/search/': typeof SearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/cuisines': typeof CuisinesIndexRoute
  '/favorites': typeof FavoritesIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/search': typeof SearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recipes/$id': typeof RecipesIdRoute
  '/cuisines/': typeof CuisinesIndexRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/search/': typeof SearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recipes/$id'
    | '/cuisines/'
    | '/favorites/'
    | '/recipes/'
    | '/search/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/recipes/$id' | '/cuisines' | '/favorites' | '/recipes' | '/search'
  id:
    | '__root__'
    | '/'
    | '/recipes/$id'
    | '/cuisines/'
    | '/favorites/'
    | '/recipes/'
    | '/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecipesIdRoute: typeof RecipesIdRoute
  CuisinesIndexRoute: typeof CuisinesIndexRoute
  FavoritesIndexRoute: typeof FavoritesIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites/': {
      id: '/favorites/'
      path: '/favorites'
      fullPath: '/favorites/'
      preLoaderRoute: typeof FavoritesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuisines/': {
      id: '/cuisines/'
      path: '/cuisines'
      fullPath: '/cuisines/'
      preLoaderRoute: typeof CuisinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecipesIdRoute: RecipesIdRoute,
  CuisinesIndexRoute: CuisinesIndexRoute,
  FavoritesIndexRoute: FavoritesIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
