/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FavoritesIndexRouteImport } from './routes/favorites.index'
import { Route as CuisineIndexRouteImport } from './routes/cuisine.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesIndexRoute = FavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => rootRouteImport,
} as any)
const CuisineIndexRoute = CuisineIndexRouteImport.update({
  id: '/cuisine/',
  path: '/cuisine/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cuisine/': typeof CuisineIndexRoute
  '/favorites/': typeof FavoritesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cuisine': typeof CuisineIndexRoute
  '/favorites': typeof FavoritesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cuisine/': typeof CuisineIndexRoute
  '/favorites/': typeof FavoritesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cuisine/' | '/favorites/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cuisine' | '/favorites'
  id: '__root__' | '/' | '/cuisine/' | '/favorites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuisineIndexRoute: typeof CuisineIndexRoute
  FavoritesIndexRoute: typeof FavoritesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites/': {
      id: '/favorites/'
      path: '/favorites'
      fullPath: '/favorites/'
      preLoaderRoute: typeof FavoritesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuisine/': {
      id: '/cuisine/'
      path: '/cuisine'
      fullPath: '/cuisine/'
      preLoaderRoute: typeof CuisineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuisineIndexRoute: CuisineIndexRoute,
  FavoritesIndexRoute: FavoritesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
